@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":ListCommandParser" as ListCommandParser LOGIC_COLOR
participant ":ListCommand" as ListCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":MatchingDepartmentPredicate" as MatchingDepartmentPredicate MODEL_COLOR
end box

[-> LogicManager : execute(list d/engineering)
activate LogicManager

LogicManager -> AddressBookParser : parseCommand(list d/engineering)
activate AddressBookParser

create ListCommandParser
AddressBookParser -> ListCommandParser : parse(d/engineering)
activate ListCommandParser

create MatchingDepartmentPredicate
ListCommandParser -> MatchingDepartmentPredicate : ListCommand(predicate)
activate MatchingDepartmentPredicate

MatchingDepartmentPredicate --> ListCommandParser
deactivate MatchingDepartmentPredicate

create ListCommand
ListCommandParser -> ListCommand : ListCommand(predicate)
activate ListCommand

ListCommand --> ListCommandParser
deactivate ListCommand

ListCommandParser --> AddressBookParser : ListCommand
deactivate ListCommandParser

AddressBookParser --> LogicManager : ListCommand
deactivate AddressBookParser

LogicManager -->[ : CommandResult
deactivate LogicManager

@enduml
